### ISSUE TITLE
maxphp的漏洞可以检测么

### ISSUE THREAD

**Issue by tab-engineer** [Lotus6/ThinkphpGUI#9]

**Comment by Lotus6** [comment]
基于Thinkphp框架写的可以检测

**Comment by Lotus6** [comment]
基于thinkphp开发的都可以检测



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chengyao ***@***.***&gt;
发送时间: 2022年5月19日 00:22
收件人: Lotus6/ThinkphpGUI ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Lotus6/ThinkphpGUI] maxphp的漏洞可以检测么 (Issue #9)
